<?php

namespace JKHBundle\Repository;

/**
 * CheckerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckerRepository extends \Doctrine\ORM\EntityRepository
{
}
