<?php

namespace JKHBundle\Repository;

/**
 * EtweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtweetRepository extends \Doctrine\ORM\EntityRepository
{
}
