<?php

namespace JKHBundle\Repository;

/**
 * User2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User2Repository extends \Doctrine\ORM\EntityRepository
{
}
