jkh_homepage:
    path:     /
    defaults: { _controller: JKHBundle:Default:index }

_jkh_auth-step1:
    path:     /auth
    defaults: { _controller: JKHBundle:Default:auth }

_jkh_auth-step2:
    path:     /auth2
    defaults: { _controller: JKHBundle:Default:auth2 }

_jkh_auth-step3:
    path:     /auth3
    defaults: { _controller: JKHBundle:Default:auth3 }

_jkh_auth-step4:
    path:     /auth4
    defaults: { _controller: JKHBundle:Default:auth4 }

_jkh_auth-step5:
    path:     /auth5
    defaults: { _controller: JKHBundle:Default:auth5 }

_jkh_auth-final:
    path:     /authfin
    defaults: { _controller: JKHBundle:Default:authfin }

_jkh_recoverypass:
    path:     /recoverypass
    defaults: { _controller: JKHBundle:Default:recoverypass }

_jkh_login:
    path:     /login
    defaults: { _controller: JKHBundle:Default:login }

_jkh_logout:
    path:     /logout
    defaults: { _controller: JKHBundle:Default:logout }