jkh_homepage:
    path:     /
    defaults: { _controller: JKHBundle:Default:index }

jkh_advert:
    path:     /advert
    defaults: { _controller: JKHBundle:Default:advert }

_jkh_orgbase:
    path:     /orgbase
    defaults: { _controller: JKHBundle:Default:orgbase }

_jkh_personalcab:
    path:     /personalcab
    defaults: { _controller: JKHBundle:Default:personalcab }

_jkh_registr:
    path:     /registr
    defaults: { _controller: JKHBundle:Default:registr }

_jkh_checkdubmail:
    path:     /checkdubmail
    defaults: { _controller: JKHBundle:Default:checkdubmail }

_jkh_checkemail:
    path:     /checkemail
    defaults: { _controller: JKHBundle:Default:checkemail }

_jkh_loginfirst:
    path:     /loginfirst
    defaults: { _controller: JKHBundle:Default:loginfirst }

_jkh_recoverypass:
    path:     /recoverypass
    defaults: { _controller: JKHBundle:Default:recoverypass }

_jkh_recoverypassletter:
    path:     /recoverypassletter/{checkmailcode}
    defaults: { _controller: JKHBundle:Default:recoverypassletter }

_jkh_changepass:
    path:     /changepass
    defaults: { _controller: JKHBundle:Default:changepass }

_jkh_changeuserinfo:
    path:     /changeuserinfo
    defaults: { _controller: JKHBundle:Default:changeuserinfo }

_jkh_deluser:
    path:     /deluser
    defaults: { _controller: JKHBundle:Default:deluser }

_jkh_login:
    path:     /login
    defaults: { _controller: JKHBundle:Default:login }

_jkh_logout:
    path:     /logout
    defaults: { _controller: JKHBundle:Default:logout }

_jkh_etweet:
    path:     /etweet
    defaults: { _controller: JKHBundle:Default:etweet }