jkh_homepage:
    path:     /
    defaults: { _controller: JKHBundle:Default:index }

jkh_advert:
    path:     /advert
    defaults: { _controller: JKHBundle:Default:advert }

_jkh_orgbase:
    path:     /orgbase
    defaults: { _controller: JKHBundle:Default:orgbase }

_jkh_registr:
    path:     /registr
    defaults: { _controller: JKHBundle:Default:registr }

_jkh_checkemail:
    path:     /checkemail/{checkmailcode}
    defaults: { _controller: JKHBundle:Default:checkemail }

_jkh_recoverypass:
    path:     /recoverypass
    defaults: { _controller: JKHBundle:Default:recoverypass }

_jkh_login:
    path:     /login
    defaults: { _controller: JKHBundle:Default:login }

_jkh_logout:
    path:     /logout
    defaults: { _controller: JKHBundle:Default:logout }

_jkh_etweet:
    path:     /etweet
    defaults: { _controller: JKHBundle:Default:etweet }